DSET_SIGNINS = "signins"
DSET_ROLE_ASSIGNMENTS = "role_assignments"
DSET_CONDITIONAL_ACCESS = "conditional_access"
DSET_MFA_COVERAGE = "mfa_coverage"
DSET_DEFENDER_ALERTS = "defender_alerts"

SUPPORTED_DATASETS = [
    DSET_SIGNINS,
    DSET_ROLE_ASSIGNMENTS,
    DSET_CONDITIONAL_ACCESS,
    DSET_MFA_COVERAGE,
    DSET_DEFENDER_ALERTS,
]
